import Header from "@/components/Header/Header";
import "./globals.css";
import Bottomheader from "@/components/Header/Bottomheader";
import Footer from "@/components/Footer";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import Providers from "@/redux/provider/provider";
import AuthProvider from "@/context/AuthProvider";

export const metadata = {
  title: "Amazon Clone with nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="font-bodyFont bg-gray-300"
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <Providers>
            <Header />
            <Bottomheader />
            {children}
            <Footer />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
